### ISSUE TITLE
Include examples in continuous integration

### ISSUE THREAD

**Issue by KaiSchu** [geo-fluid-dynamics/phaseflow-fenics#121]
Just an idea:
The README in the examples folder says
> Here we have examples that take too long to run to consider including them
in the continuous integration test suite.

Maybe it would be worth to include them by temporarely (via a script) changing the number of time steps to one. So you could at least check if they will be executed correctly.

**Comment by alexanderzimmerman** [comment]
You're right that this would be far better than not automatically running them at all. Actually someone pointed out to me the other day that Travis can do nightly builds, so I think I'll first try that. I had forgotten to put this on my list and it slipped my mind, so thanks for calling my attention to it again :)

**Comment by alexanderzimmerman** [comment]
Ah I guess it didn't entirely slip my mind. This is connected to issue #113. So to summarize, at least until the examples become even more expensive, I'm going to have Travis run them in a nightly build.

**Comment by alexanderzimmerman** [comment]
I'm closing this because it's redundant with (the still unresolved) issue #113.
