### ISSUE TITLE
Consider using erf instead of tanh

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#127]
The regularization published in danaila2014newton doesn't make physical sense. Others have used the error function (erf), which can be easily constrained to be exactly zero at a specific temperature and exactly one at a specific temperature.

**Comment by agzimmerman** [comment]
I describe the regularization more generally and use a erf regularization in [my submitted paper](https://www.researchgate.net/publication/334388440_Simulating_convection-coupled_phase-change_in_enthalpy_form_with_mixed_finite_elements).
