### ISSUE TITLE
Verify with the method of manufactured solution (MMS)

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#158]
See [Sandia's report on code verification by the method of manufactured solutions](http://prod.sandia.gov/techlib/access-control.cgi/2000/001444.pdf).

**Comment by alexanderzimmerman** [comment]
Make sure to check the quadrature degree (for which we usually choose less than the exact degree) if convergence isn't optimal.

**Comment by agzimmerman** [comment]
I wasn't able to get the Dirichlet BC's, based on manufactured solutions, to work properly with FEniCS. It appeared to be a bug in the `fenics.DirichletBC` interface. I recall discussing the issue on Slack, but I do not recall documenting a bug (e.g. on their BitBucket).

On the other hand, this worked exactly as expected with Firedrake, so I have many examples of MMS verification in the [Sapphire](https://github.com/geo-fluid-dynamics/sapphire) repository.
