### ISSUE TITLE
Bound the regularization smoothing factor $r$

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#190]

**Comment by alexanderzimmerman** [comment]
Perhaps we can ramp $r$, similar to how one might ramp boundary conditions to help the Newton method converge. So for a given time step, we can first obtain a solution for large $r$, and then reduce $r$ sequentially. I'm not yet sure how difficult this will be to do with AMR.

**Comment by alexanderzimmerman** [comment]
That idea from April works quite nicely. Still there seems to always be a lower limit for $r$. This is probably dependent on some parameters, most importantly the grid spacing near the phase interface. We have yet to quantify this.

**Comment by agzimmerman** [comment]
Using the continuation algorithm in [my submitted paper](https://www.researchgate.net/publication/334388440_Simulating_convection-coupled_phase-change_in_enthalpy_form_with_mixed_finite_elements), it is not troublesome to reduce $r$ until the interface is limited by the mesh cell size.
