### ISSUE TITLE
Stefan problem benchmark

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#23]
In danaila2014newton, the third benchmark adds both the variable viscosity nonlinearity and the phase-change enthalpy source nonlinearity. Both of these are difficult additions, and since I am currently unsuccessful at reproducing the benchmark, I am trying an example that only introduces the latter. Beyond simply helping us debug this code, the Stefan problem benchmark, especially a 3D analogy, may be a useful contribution, or rather an interesting example application of Danaila's method.

To resolve this issue...
1. verify against the exact solution, e.g. from Kai's MATLAB script.
2. explore numerical limits, e.g. high and low Stefan Number. Possibly relate time step size and grid spacing to the Stefan Number.
3. Attempt adaptive mesh refinement for this 1D problem.

**Comment by alexanderzimmerman** [comment]
This works on the stefan_problem branch as of 0dc0d4ab263887de9937060a5e09d03827b78cff

The branch still needs to be merged.

**Comment by alexanderzimmerman** [comment]
When all parameters are set to unity, this looks great!

![compare](https://user-images.githubusercontent.com/9367569/28278175-6f9a9cde-6b1c-11e7-86bb-fa1e1cc0e58c.png)

As we would expect, the differences at later times come from the Stefan Problem effectively having a Neumann boundary condition infinitely far away, rather than a Dirichlet boundary condition at $x = 1$. The difference at time $t = 0.001$ is more interesting, and may be a numerical discretization error.

**Comment by alexanderzimmerman** [comment]
Test code which verifies the position of the PCI was added in commit e209dc55b89b00eab7a8bd00577622f378df2fcf

**Comment by alexanderzimmerman** [comment]
Presently this works for Stefan Numbers 1 and 0.1, but fails for 0.01. I began experimenting with the regularization parameters, grid size, and time step size. Now I set those parameters aside, and am focusing on adaptively refining the mesh cells which contain the PCI.

I'm making some good progress on the branch https://github.com/geo-fluid-dynamics/phaseflow-fenics/tree/feature/refine_near_pci

In the following figure (which used $Ste = 1.$), things run well for a while, and then the Newton method fails miserably.
![solvedtimes](https://user-images.githubusercontent.com/9367569/28383132-bb35418a-6cc0-11e7-87ec-57b5e2840aef.png)
![failednewton](https://user-images.githubusercontent.com/9367569/28383134-bce466aa-6cc0-11e7-8e02-aa7ac2f07d99.png)

Having not had time to dig into this bug yet, I'm guessing it has to do with how I'm preserving the solution from the most recent Newton iteration, even when the Newton iterations fail to converge and I adaptively refine the mesh (and then continue the Newton iterations).

**Comment by alexanderzimmerman** [comment]
As of commit d9eacbd76f34aaaa6f528149654d52e2eb11fe0e, adaptive refinement of mesh cells containing the PCI appears to work well in 1D. The following figure is for the outputs of test_stefan_problem_pci_refinement:

![amr_compare](https://user-images.githubusercontent.com/9367569/28423588-b8002c72-6d6b-11e7-97a4-e7fded10621b.png)

The line markers are at mesh vertices. The initial mesh was refined by bisection repeatedly near the hot wall, with the initial temperatures. While integrating in time, whenever the Newton method failed to converge, mesh cells containing the PCI were bisected.

**Comment by alexanderzimmerman** [comment]
We can handle low Stefan numbers (down to 0.01) as of commit 0b6642dcfd048c621f0ac996e4844d700fe1f743.

The benchmark from danaila2014newton that has been giving me so much trouble used $Ste = 0.045$, so today's progress is quite promising.

Here again is the comparison to the analytical solution:
![compare_ste0p01](https://user-images.githubusercontent.com/9367569/28429906-c3eb0814-6d7e-11e7-88e4-dbe0727644be.png)

Now before closing this issue, I want to discuss goals for this benchmark with @julekowalski.

**Comment by julekowalski** [comment]
Hi Alex, this indeed looks promising. So what was it in the end?
There is a slight undershoot at the next to the kink at t=0.1. Is this sensitive to the grid resolution?
Regarding the benchmark: Is this solution a cut through a 2d calculation? Or is it solved in 1d? Next thing I would see relevant to do is of this result carries over to general 2d (or maybe even 3d) calculations.
Best, Julia

**Comment by alexanderzimmerman** [comment]
Getting this to work was a combination of... 1. automatically refining the mesh cells containing the PCI, and 2. playing with the parameters for regularization, time stepping, Newton tolerance, and even the initial spatial grid resolution. Right now I'm completing a test suite where all of this will be clarified.

I haven't tried fixing that undershoot yet; but my first guess is that tightening the Newton tolerance (which should also cause additional grid refinement, using my algorithm) will solve it. So yes, it should be sensitive to grid resolution, though I have not yet directly observed it for this problem. I'll make sure to look into that before closing this issue.

This is a proper 1D formulation. I agree about extending to 2D and 3D. I think I'll move on to the variable viscosity problem before the 3D extension; and I think I'll open a new issue for extending this benchmark to 2D/3D. Do we still call it a "Stefan problem" at that point, or is there a better way to think about the benchmark?

**Comment by julekowalski** [comment]
Hi Alex,
the 2d extension will still be a Stefan problem. It's just that we do not have a nice closed analytical solution for it. The viscosity coupling makes sense only in 2d, so a natural order of procedures would be:
2d-Stefan problem mimicking 1d behavior,
a 'real' 2d-Stefan problem, and then
viscosity coupling in 2d
Then we should be able to do the paper ..
Best, Julia

**Comment by alexanderzimmerman** [comment]
Thanks for the nice summary. So based on our recent conversations, I threw together a quick chart showing a "test matrix" for the capabilities we're aiming for in the scope of my lectures in September (granting that we might not complete everything we wanted):

![testmatrix](https://user-images.githubusercontent.com/9367569/28468726-1efeb182-6e34-11e7-9b8a-7bb5dc3d9aad.PNG)

The amount of blue ink might look daunting, but a lot of that should fill with green quite quickly. The biggest risk right now is getting the variable viscosity to work; but I haven't highlighted it as a problem, since I haven't actually taken any time to properly dissect that component.

**Comment by alexanderzimmerman** [comment]
The simple 2D Stefan Problem (where the 1D problem is simply extruded in the Y dimension) looks correct for unit Stefan Number. It is taking quite some time to compute lower Stefan Numbers on my laptop. Here's the $Ste = 1$ result:

![compare_with_2d_slice](https://user-images.githubusercontent.com/9367569/28663994-3b878416-72bf-11e7-9635-6adb7afc635f.png)

Note that the mesh becomes quite coarse as the X coordinate increases.

**Comment by julekowalski** [comment]
good, try with a different temperature on the right hand side of the domain. Even with the same Stefan number you should see a more clearly distinct 'kink'. You can test this with the exact solution ...
Best, J

**Comment by alexanderzimmerman** [comment]
As part of this benchmark, we are also exploring the details of the regularization.

Today Julia noticed that the parameters a_s and R_s should really just be a single parameter. So that simplifies things a bit.

As part of this benchmark issue, we're planning to explore how a_s (or R_s), the grid spacing, and the Stefan Number affect convergence of the Newton method. This can be mostly done in 1D; but we should verify that the results extend to 2D.

**Comment by alexanderzimmerman** [comment]
As of PR #167 , our result for this benchmark is quite good, and is a of the submitted ICCE proceedings paper.

We still have some open issues that were discussed in this thread:
- Time step size discussion is now issue #189
- Regularization discussion is now issue #190
- The Newton method's sensitivity to the initial mesh is now issue #191

Also regarding other discussion items from this thread:
- I no longer play with the Newton method's tolerance. This is 1.e-8 by default, which is working for all current tests.
- The results posted earlier in this thread used the old adaptivity procedure, which was quite ad-hoc. Now we use the standard algorithm of fenics.AdaptiveNonlinearVariationalSolver.
- We never did a 2D Stefan problem, e.g. something with a hot plate on the side and the bottom (similar to Kai's experiment). Maybe this would still be interesting, but now we do have a good result for the analogous convection-coupled problem, which is more difficult.
