### ISSUE TITLE
Clarify the LBB inf-sup stability condition

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#236]
PR #234 supports that the combination of both the penalty method and Taylor-Hood elements might be necessary for the mixed formulation with the energy. I think it's misleading to only talk about the penalty method and Taylor-Hood elements in context of incompressible Navier-Stokes, as is does in Danaila's paper as as I continued to do in my contributions. It seems to me that the details are quite different. Deriving the LBB condition would be very nice.

**Comment by alexanderzimmerman** [comment]
This is related to #235, where we briefly tried using linear velocity elements (while keeping the penalty stabilization).

**Comment by agzimmerman** [comment]
I didn't do the analysis; but empirically, equal-order elements do work with the penalty method, as I show in [this paper](https://www.researchgate.net/publication/334388440_Simulating_convection-coupled_phase-change_in_enthalpy_form_with_mixed_finite_elements).
