### ISSUE TITLE
Document adaptive mesh refinement (AMR) procedure

### ISSUE THREAD

**Issue by alexanderzimmerman** [geo-fluid-dynamics/phaseflow-fenics#86]

**Comment by alexanderzimmerman** [comment]
Now that I've dug through their references more thoroughly, it's clear that our approaches to adaptive refinement are radically different.

The AMR approach in danaila2014newton is definitely not what we want for Phaseflow; but we may end up wanting to try it for the purposes of reproducing their results.

**Comment by alexanderzimmerman** [comment]
We've moved forward with the dual-weighted residual method for goal-oriented AMR, which is what's used by fenics.AdaptiveNonlinearVariationalSolver.

Reproducing exactly what was done in danaila2014newton would be quite difficult without collaboration, since the paper does not say exactly which metrics are used, and we have no experience with the FEM software library they used.

**Comment by alexanderzimmerman** [comment]
Addressing issue #48 requires a better understanding of the AMR algorithm.

**Comment by alexanderzimmerman** [comment]
From the [in-source documentation](https://fenicsproject.org/olddocs/dolfin/1.3.0/python/programmers-reference/cpp/fem/Extrapolation.html):

```
  /// A class for goal-oriented adaptive solution of nonlinear
  /// variational problems.
  ///
  /// For a nonlinear variational problem of the form: find u in V
  /// satisfying
  ///
  ///     F(u; v) = 0 for all v in :math:`\hat V`
  ///
  /// and a corresponding conforming discrete problem: find u_h in V_h
  /// satisfying (at least approximately)
  ///
  ///     F(u_h; v) = 0 for all v in :math:`\hat V_h`
  ///
  /// and a given goal functional M and tolerance tol, the aim is to
  /// find a V_H and a u_H in V_H satisfying the discrete problem such
  /// that
  ///
  ///     \|M(u) - M(u_H)\| < tol
  ///
  /// This strategy is based on dual-weighted residual error
  /// estimators designed and automatically generated for the primal
  /// problem and subsequent h-adaptivity.

  class AdaptiveNonlinearVariationalSolver
    : public GenericAdaptiveVariationalSolver
  {
```

**Comment by agzimmerman** [comment]
The approach is documented in [my conference paper](https://www.researchgate.net/publication/327146270_Monolithic_Simulation_of_Convection-Coupled_Phase-Change_Verification_and_Reproducibility_Proceedings_of_the_4th_International_Conference_on_Computational_Engineering_ICCE_2017_in_Darmstadt?_sg=6-ifvIVhCqTxMcZUwTEBECV5bOvdvgfqkuvQUCFyJPteQNcl7Yw5MvLLC6dgeqQ1Op3wZ81wf-RyBlq282QKAhentDsA3fOlVeXStIbD.VtU8EBfS3JRWivaSFgxwyFGiAocVdRBd0vX72wH9XCy9X7sdrrdle8WCagiY-vkidePmhSwRtq0gWfZLg4fBwg).
